### ISSUE TITLE
Disable buttons in the UI if the required envs are missing

### ISSUE THREAD

**Issue by blankdots** [CSCfi/sda-filesystem#25]
if `FS_SD_CONNECT_METADATA_API` and `FS_SD_CONNECT_DATA_API` are missing we can disable the `SD Connect` button
if `FS_SD_SUBMIT_API` is missing disable `SD Apply` button in the UI

**Comment by juhtornr** [comment]
Lets gray out the UI components / services that are not enabled (meaning ENVs are missing).

**Comment by blankdots** [comment]
We should disable the button for `SD Apply` if we fail to retrieve datasets with the token
![image](https://user-images.githubusercontent.com/47524/158587322-566a60ef-cc97-4d8b-9f2b-e82faa1285cd.png)

also maybe a better message than `invalid token` as that is not accurate, the token is valid but there are no datasets
![image](https://user-images.githubusercontent.com/47524/158587512-608db658-47a7-4420-82c3-bf79d0e3a182.png)

my comment can be done in a separate issue, however mentioning it here as it seemed related
