### ISSUE TITLE
New versions of SD connect might require sending access token

### ISSUE THREAD

**Issue by blankdots** [CSCfi/sda-filesystem#30]
new versions of the `SD Connect` might require sending `SDS_ACCESS_TOKEN` due to additional checks being done, by reverse proxy in front of the API

**More details required**

**Comment by teemukataja** [comment]
For all APIs:
```
Authorization: Bearer SDS_ACCESS_TOKEN
```
For SD-Connect API, rename `Authorization` to `X-Authorization`
```
X-Authorization: Basic base64_token
X-Authorization: Bearer openstack_token
```
