### ISSUE TITLE
SD-Connect API merger

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/sda-filesystem#33]
SD-Connect Data-API and Metadata-API are going to be merged into a single app. Old endpoints stay the same. Instead of two environment variables we're going to need only one.

Old
```
export FS_SD_CONNECT_METADATA_API=https://connect-metadata-api-test.sd.csc.fi
export FS_SD_CONNECT_DATA_API=https://connect-data-api-test.sd.csc.fi
```
New, e.g.
```
export FS_SD_CONNECT_API=https://connect-api-test.sd.csc.fi
```

**Comment by blankdots** [comment]
we also need to update docs with this issue
